apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-test-order-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-test-order-management-service
  template:
    metadata:
      labels:
        app: lab-test-order-management-service
    spec:
      containers:
      - name: lab-test-order-management-service
        image: yjb28/lab-test-order-management-service:v17
---
apiVersion: v1
kind: Service
metadata:
  name: lab-test-order-management-service
spec:
  selector:
    app: lab-test-order-management-service
  ports:
  - name: tcp
    port: 8080
    targetPort: 8080
    nodePort: 30013
  type: LoadBalancer
