apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-test-cart-management-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-test-cart-management-service
  template:
    metadata:
      labels:
        app: lab-test-cart-management-service
    spec:
      containers:
      - name: lab-test-cart-management-service
        image: yjb28/LabCart:v1
---
apiVersion: v1
kind: Service
metadata:
  name: lab-test-cart-management-service
spec:
  selector:
    app: lab-test-cart-management-service
  ports:
  - name: tcp
    port: 8080
    targetPort: 8080
    nodePort: 30014
  type: LoadBalancer
