apiVersion: apps/v1
kind: Deployment
metadata:
  name: labs-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labs-management-service
  template:
    metadata:
      labels:
        app: labs-management-service
    spec:
      containers:
      - name: labs-management-service
        image: yjb28/labs-management-service:v15
---
apiVersion: v1
kind: Service
metadata:
  name: labs-management-service
spec:
  selector:
    app: labs-management-service
  ports:
  - name: tcp
    port: 8080
    targetPort: 8080
    nodePort: 30016
  type: LoadBalancer
